name:                validators
synopsis:            Composable validations for your Haskell data types
version:             0.0.1
homepage:            https://github.com/luc-tielen/validators#README.md
license:             MIT
author:              Luc Tielen
maintainer:          luc.tielen@gmail.com
copyright:           2019 Luc Tielen
category:            Data
extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE

dependencies:
  - base >= 4.12 && < 5
  - containers == 0.*
  - text == 1.*

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

library:
  source-dirs:        lib

tests:
  validators-test:
    main:             test.hs
    source-dirs:      tests
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - validators

  validators-doctest:
    main:             doctest.hs
    source-dirs:      tests
    ghc-options:      -threaded
    dependencies:
      - doctest >= 0.16.1 && < 1
      - hspec >= 2.6.1 && < 3.0.0
      - Glob >= 0.10.0 && < 1
      - validators
