version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci

    steps:
      - checkout
      - run:
          name: Build, run tests
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            USER=$(whoami) cachix use luctielen
            nix-shell --arg isDevBuild "false" --option sandbox false --run "make configure tests"
            nix-shell --arg isDevBuild "false" --option sandbox false --run "cabal new-build lib:validators"
            nix-shell --arg isDevBuild "false" --option sandbox false --run "make lint format_check"
